---
version: '3.5'
services:

  connect:
    volumes:
      - ../../connect/connect-http-sink/security:/tmp
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-http
